### ISSUE TITLE
video editing: gopro 360 footage - stich & edit

### ISSUE THREAD

**Issue by devinschumacher** [serpcompany/public#11]
# DESCRIPTION

We are seeking a skilled GoPro 360 video editor to help with a few video editing tasks:

## Pre edits

Our "pre-edit" phase is simply a "stitch edit" of the 360 videos; aka using the [GoPro Quik App](https://gopro.com/en/us/shop/quik-app-video-photo-editor) to re-frame & re-level the raw footage by stitching & leveling to always keep the "focus" (subject, subject matter, etc.) in frame & keep the frame level.

## Edits

After the pre-edits, the footage will be editing for various social platforms. This may include things like:

- editing the content at various lengths for different platforms
- editing the content at various aspect ratios for different platforms
- color correction, adding music, adding subtitles, etc. (when appropriate)
- enhance video quality through color correction, audio adjustments, music and visual effects.
- incorporate graphics, text overlays, captions, etc.

# EXPECTATIONS

The main content we are editing first will be "boxing sparring" videos. Each round is 3 mins of footage. A "pre-edit" should take about 15-20 minutes to do with the GoPro Quik app.

## Trial task resources

If you're doing the trial task, pick one of the videos below, download it & do the "pre-edit" phase:

- [ ] 1: [devin_marco_sparring_rd1.360](https://mega.nz/folder/80Fl3SBb#9MvOCFZIgQcpLEQQij9zBw/file/M80gCBIJ)
- [ ] 2: [devin_marco_sparring_rd2.360](https://mega.nz/folder/80Fl3SBb#9MvOCFZIgQcpLEQQij9zBw/file/0l9gGJia)
- [ ] 3: [devin_marco_sparring_rd3.360](https://mega.nz/folder/80Fl3SBb#9MvOCFZIgQcpLEQQij9zBw/file/8x10FDTY)

**Comment by devinschumacher** [comment]
done.
