### ISSUE TITLE
website: `serp.media` - "movies" collection

### ISSUE THREAD

**Issue by devinschumacher** [serpcompany/public#6]
For this task, please go through the process of adding a new "collection" to the theme, called `movies`. 

Please film a loom video so I can have my team turn the process into an SOP (so we can update some of the other projects as well).

## todos

- [ ] create a collection for src/content/movies/
- [ ] add in some of the "movies" files below to make sure they work
- [ ] A place in the /sitemap-index.xml for the  `/movies/` collection
- [ ] The posts will display on a `/movies/` slug as a collection,
- [ ] "Category" tags in the "movies" frontmatter link the "movies" posts together
- [ ] A section on the homepage under the "Posts" area for the "Movies" recent posts
- [ ] A place in the /sitemap-index.xml for the  `/movies/` collection

* Do your work on a BRANCH and submit a PR when done. include the loom.com video link in the PR

## Resources

- [example "movies" .md files](https://drive.google.com/file/d/1IIuGhVHLI_fsvP8_Q0TNO3Cf1cMtjxlF/view?usp=drive_link)
- repo: https://github.com/serpcompany/serp.media

**Comment by devinschumacher** [comment]
complete
